[workspace]
authors = ["m9o8 <mope6498@gmail.com>"]
channels = ["conda-forge"]
name = "bse_tm_final"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.1.0,<8"
jupyter = ">=1.1.1,<2"
polars = ">=1.35.1,<2"
lxml = ">=6.0.2,<7"
psutil = ">=7.1.3,<8"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
py7zr = ">=1.0.0,<2"
statsmodels = ">=0.14.5,<0.15"
pandas = ">=2.3.3,<3"
